In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display

In [2]:
## Внимание код работает в версии 1.0
import sklearn
sklearn.__version__

'1.6.1'

## Ordinal Encoder

In [3]:
from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()
X = [['Male', 1], ['Female', 3], ['Female', 2],['Gender',1],['Gender',10],['Gender',3]]
enc.fit(X)
enc.categories_

[array(['Female', 'Gender', 'Male'], dtype=object),
 array([1, 2, 3, 10], dtype=object)]

In [5]:
enc.transform([['Female', 3], ['Male', 1],['Gender',10]])

array([[0., 2.],
       [2., 0.],
       [1., 3.]])

In [12]:
enc.categories_

[array(['Female', 'Gender', 'Male'], dtype=object),
 array([1, 2, 3, 10], dtype=object)]

In [14]:
enc.inverse_transform([[1, 0], [0, 3]])

array([['Gender', 1],
       ['Female', 10]], dtype=object)

## LabelEncoder

In [17]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit([1, 2, 2, 6])
le.classes_

array([1, 2, 6])

In [19]:
le.transform([1, 1, 2, 6])

array([0, 0, 1, 2])

In [21]:
le.inverse_transform([0, 0, 1, 2])

array([1, 1, 2, 6])

In [23]:
le = preprocessing.LabelEncoder()
le.fit(["paris", "paris", "tokyo", "amsterdam"])
le.classes_

array(['amsterdam', 'paris', 'tokyo'], dtype='<U9')

In [25]:
le.transform(["tokyo", "tokyo", "paris"])

array([2, 2, 1])

In [27]:
le.inverse_transform([2, 2, 1])

array(['tokyo', 'tokyo', 'paris'], dtype='<U9')

## OneHotEncoder

In [14]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')#
X = [['Male', 1], ['Female', 3], ['Female', 2]]
enc.fit(X)
enc.categories_

[array(['Female', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]

In [15]:
# handle_unknown='ignore' ВНИМАНИЕ неивестные обращаются в 0-вектор
enc.transform([['Female', 1], ['Male', 10]]).toarray()

array([[1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [3]:
enc.inverse_transform([[0, 1, 1, 0, 0], [0, 0, 0, 1, 0]])

array([['Male', 1],
       [None, 2]], dtype=object)

In [36]:
enc.get_feature_names_out(['gender', 'group'])

array(['gender_Female', 'gender_Male', 'group_1', 'group_2', 'group_3'],
      dtype=object)

In [38]:
drop_enc = OneHotEncoder(drop='first').fit(X)
drop_enc.categories_

[array(['Female', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]

In [40]:
drop_enc.transform([['Female', 1], ['Male', 2]]).toarray()

array([[0., 0., 0.],
       [1., 1., 0.]])

In [42]:
drop_binary_enc = OneHotEncoder(drop='if_binary').fit(X)
drop_binary_enc.transform([['Female', 1], ['Male', 2],['Female', 1]]).toarray()

array([[0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.]])